name: Flask CI/CD Pipeline

on:
  push:
    branches: [ development ]  
  pull_request:
    branches: [ development ] 

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run tests
      run: |
        pytest

    - name: Deploy to Heroku
      if: github.ref == 'refs/heads/master' && job.status == 'success'
      run: |
        heroku login -i
        git push heroku master
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}    