"""add image url to animals table

Revision ID: 687568fc211b
Revises: e606cf991aec
Create Date: 2024-05-08 15:08:31.578831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '687568fc211b'
down_revision = 'e606cf991aec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('animals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('animals', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
